punker76/gong-wpf-dragdrop

- Examples/DefaultsExample/Window(NET4).xaml
- GongSolutions.Wpf.DragDrop/DragDrop.cs
- GongSolutions.Wpf.DragDrop/DragInfo.cs
Don't search for closest item. This allows to start selection when drag starts on empty space inside ListBox. Can be used with [that behavior](http://www.codeproject.com/Articles/209560/ListBox-drag-selection) after some changes in OnPreviewMouseLeftButtonDown.
> Added DragDirectlySelectedOnly

- Examples/NorthwindExample/Views/EmployeesTabView(NET4).xaml
- GongSolutions.Wpf.DragDrop/DefaultDropHandler.cs
- GongSolutions.Wpf.DragDrop/DragDrop.cs
Added optional DragDropContext dependency property for declarative of
DragDrop operations. Useful when users may have 2+ drag targets/sources
where source and destination need to be constrained.
Closes #89
> Support for DragDropContext #89

- GongSolutions.Wpf.DragDrop/DropTargetInsertionAdorner.cs
- GongSolutions.Wpf.DragDrop/Utilities/ItemsControlExtensions.cs
If we drag after last item in grouped list, assume to move it at the end.
> Support drag after last item in grouped list

- .editorconfig
- Examples/DefaultsExample/Data.cs
- Examples/DefaultsExample/Window(NET4).xaml
- GongSolutions.Wpf.DragDrop (NET4).sln.GhostDoc.xml
- GongSolutions.Wpf.DragDrop/DefaultDropHandler.cs
- GongSolutions.Wpf.DragDrop/DragDrop.cs
- GongSolutions.Wpf.DragDrop/DropInfo.cs
- GongSolutions.Wpf.DragDrop/Utilities/TypeUtilities.cs
- call DragOver in drop event too
- ICloneable support for copy or link effect
- rename `ToList` -> `TryGetList` and check for `IList`
Closes  #106 Dragging between controls creates a shallow copy
> Default drop handler changes

- GongSolutions.Wpf.DragDrop/Utilities/VisualTreeExtensions.cs
When using a scroll viewer on a custom control the given ContentPresenter isn't correctly returned by the `GetVisualAncestor()` method. Because there are 2 (the scrollcontentpresenter and the own contentpresenter). Therefore the Collection can't be determinate, and a null reference exception will be thrown.
Example Control
```
<Style TargetType="{x:Type local:CustomControl1}">
<Setter Property="Template">
<Setter.Value>
<ControlTemplate TargetType="{x:Type local:CustomControl1}">
<Border Background="Red">
<ScrollViewer>
<ItemsPresenter />
</ScrollViewer>
</Border>
</ControlTemplate>
</Setter.Value>
</Setter>
</Style>
``` 
and the class file
```
public class CustomControl1 : ItemsControl
{
public IDragSource DragHandler
{
get { return …
```
> Fix an issue when the itempresenter contains more ContentControls

- GongSolutions.Wpf.DragDrop/DragDrop.cs
- GongSolutions.Wpf.DragDrop/Utilities/ItemsControlExtensions.cs
Closes #127 Shift + Click item of multi-selectable Listbox doesn't work as windows file explorer
> fix for shift-click multiselection

- Examples/DefaultsExample/Data.cs
- Examples/DefaultsExample/MainWindow.xaml
- GongSolutions.Wpf.DragDrop/DefaultDropHandler.cs
- GongSolutions.Wpf.DragDrop/DragDrop.cs
- GongSolutions.Wpf.DragDrop/DropInfo.cs
- GongSolutions.Wpf.DragDrop/GongSolutions.Wpf.DragDrop.ALPHA.nuspec
- GongSolutions.Wpf.DragDrop/Properties/AssemblyInfo.cs
- GongSolutions.Wpf.DragDrop/Utilities/ItemsControlExtensions.cs
grab the latest alpha: https://www.nuget.org/packages/gong-wpf-dragdrop/
Closes #109
> TabControl support and some improvements

- GongSolutions.Wpf.DragDrop/DragDrop.cs
- GongSolutions.Wpf.DragDrop/DropInfo.cs
Consider a listbox bound to a collection representing groups of items. You want to drag into the list *or* in an *item*. The item implements IDropTarget, and you need it to show HighlightAdorner - but that only works on a valid VisualTargetItem which is only set on ItemsControls. Added code to fallback setting VisualTargetItem = VisualTarget, and checking for target adorner on any target UIElement.
> Allow target adorners on non-ItemsControls

- GongSolutions.Wpf.DragDrop/DefaultDragHandler.cs
Hi! Thank you for the great library!
I want to inherit from `DefaultDragHandler` to ignore `NumericUpDown` from `MahApps` as you did with `TextBox`, `ComboBox`, etc.
As I can see there is no reason to not allow to override `CanStartDrag`.
> Make DefaultDragHandler.CanStartDrag virtual

- GongSolutions.Wpf.DragDrop/DefaultDropHandler.cs
copy only if needed
- fixed HasFlag usage (I should do this for other places too)
- allow copy action if source=target
- don't allow if source item is headered (items) control or list box item
Closes #162 Copy function doesn't seem to work
> Fix for copy functionallity

- GongSolutions.Wpf.DragDrop/DragDrop.cs
- GongSolutions.Wpf.DragDrop/GongSolutions.Wpf.DragDrop (NET35).csproj
- GongSolutions.Wpf.DragDrop/GongSolutions.Wpf.DragDrop (NET4).csproj
- GongSolutions.Wpf.DragDrop/Utilities/RootElementFinder.cs
Signed-off-by: Rico-E <reissmann@advitec.de>
> Find correct current adorner layer (root element)

- GongSolutions.Wpf.DragDrop/DragDrop.cs
Effect & drag adorners weren't displayed when the target was not on the same root element (Window etc) than the source. This commit fixes the issue.
> Use target root element to display adorners

- src/GongSolutions.WPF.DragDrop/DragDrop.cs
- src/Showcase.WPF.DragDrop.NET45/Models/ItemModel.cs
- src/Showcase.WPF.DragDrop.NET45/Views/MixedSamples.xaml
Some fixes for the hit test problem
- Allow ButtonBase controls at mouse down of source control
- Test for the correct source start control at mouse move
Closes #213 Support for ControlTemplate types
Closes #212 No Handler is called if ListView is inside Expander in DataTemplate
Closes #145 Generalized drag-checks for scrollbar etc.
> Hit test DragDrop start fixes

- src/GongSolutions.WPF.DragDrop.Shared/Utilities/ItemsControlExtensions.cs
When dragging an item from an ItemsControl using a CollectionViewSource with groups, IDropInfo.Data was incorrectly referencing the item's group and not the item itself, causing unexpected behavior.
This fixed the issue in our use case, though I must say I'm not sure if it has any side effect.
```csharp
public class VM
{
public CollectionViewSource ItemsCollectionViewSource { get; protected set; }
public class Item
{
public string Name { get; set; }
public string GroupName { get; set; }
}
public List<Item> items = new List<Item>()
{
new Item() { Name = "Item1", GroupName = "Group1" },
new Item() { Name = "Item2", GroupName = "Group1" },
new Item() { Name = "Item3", GroupName = "Group2" },
new Item() { Name = "Item4", GroupName = "Group2" },
new Item() { Name = "Item5", GroupName = …
```
> Fix IDropInfo.Data when dragging from an ItemsControl using a CollectionViewSource with groups

- src/GongSolutions.WPF.DragDrop.Shared/DragInfo.cs
When dragging a selected item, the drag info contains the previously selected items.
- The control has still the old selected items at the mouse down event, so we should check this and give only the real selected item to the user.
Closes #258
> Fix #258 wrong dragged item

- src/GongSolutions.WPF.DragDrop.Shared/DragDrop.cs
If the user has a custom DataObject then it should directly be used for the drag drop operation.
Closes #255
> Fix for #255 using custom DataObject

- src/GongSolutions.WPF.DragDrop.Shared/DragDrop.cs
- src/GongSolutions.WPF.DragDrop.Shared/DragInfo.cs
The main problem for this issue and #258 is that in the previewed mouse down event the selected items are still the previous ones.
Closed #264 
Relates to #264
> (#264) Fix Ctrl-Click and drag only drags most recently selected item

- src/GongSolutions.WPF.DragDrop.Shared/DragDrop.cs
- src/GongSolutions.WPF.DragDrop.Shared/DropInfo.cs
- src/GongSolutions.WPF.DragDrop.Shared/IDropInfo.cs
I've added the feature to customize the text which pops up when you drag an item by adding an optional argument to the GetEffectAdornerTemplate function.
Before, you only could choose between "Move to", "Copy to", "Link to" and no text at all.
If you leave the string empty or null the default strings will be used.
I extended the IDropInfo interface with the EffectText string.
> Added custom effect text

- src/GongSolutions.WPF.DragDrop.Shared/DropInfo.cs
Fix for dragging an item over a nested ListView which is not a DropTarget.
The VisualTargetItem and TargetItem was not set after searching with GetItemContainerAt.
Closes #244 
Relates to #244
> Fix for dragging an item over a nested ListView

- src/GongSolutions.WPF.DragDrop.Shared/DragDrop.Properties.cs
- src/GongSolutions.WPF.DragDrop.Shared/DropTargetInsertionAdorner.cs
- src/Showcase.WPF.DragDrop.NET45/Views/ListBoxSamples.xaml
The ShowAlwaysDropTargetAdorner gets or sets whether to show the DropTargetAdorner (DropTargetInsertionAdorner) on an empty target too.
Closes #203 
Relates to #203
> New attached property ShowAlwaysDropTargetAdorner

- src/GongSolutions.WPF.DragDrop.Shared/DragDrop.Properties.cs
- src/GongSolutions.WPF.DragDrop.Shared/DragDrop.cs
- src/GongSolutions.WPF.DragDrop.Shared/DragInfo.cs
- src/GongSolutions.WPF.DragDrop.Shared/DropInfo.cs
- src/GongSolutions.WPF.DragDrop.Shared/IDragInfo.cs
With these changes it will be possible to use a custom `DataFormat` for the drag&drop actions.
- New property `DataFormat` at `IDragInfo` (default is DragDrop.DataFormat)
- New attached property DataFormat (default is DragDrop.DataFormat)
- The DragInfo will use the default DragDrop.DataFormat if there is no DataFormat set via attached property. It's also possible to override this at the `StartDrag` method.
- The `DataObject` will then use the DataFormat from the drag info.
Closes #269 
Relates to #269
> (#269) Using own DataFormat for Drag&Drop action

- src/GongSolutions.WPF.DragDrop.Shared/DefaultDragHandler.cs
- src/GongSolutions.WPF.DragDrop.Shared/DragDrop.cs
- src/GongSolutions.WPF.DragDrop.Shared/IDragSource.cs
- src/Showcase.WPF.DragDrop.NET45/MainWindow.xaml
- src/Showcase.WPF.DragDrop.NET45/MainWindow.xaml.cs
- src/Showcase.WPF.DragDrop.NET45/Models/ItemModel.cs
- src/Showcase.WPF.DragDrop.NET45/Models/SampleData.cs
- src/Showcase.WPF.DragDrop.NET45/Models/SerializableDragHandler.cs
- src/Showcase.WPF.DragDrop.NET45/Models/SerializableDropHandler.cs
- src/Showcase.WPF.DragDrop.NET45/Showcase.WPF.DragDrop.NET45.csproj
- src/Showcase.WPF.DragDrop.NET45/Views/ListBoxSamples.xaml
- src/Showcase.WPF.DragDrop.NET45/Views/MixedSamples.xaml
- src/Showcase.WPF.DragDrop.NET45/Views/MixedSamples.xaml.cs
This PR adds a new method to the IDragSource interface and adds a sample to show a drag&drop from one app to another with a serializable model.
- New DragDropOperationFinished method for IDragSource
- Add serializable sample
Closes #254 
Closes #136 
Relates to #136 
Relates to #29
> Drag&Drop from App to App

- src/GongSolutions.WPF.DragDrop.Shared/DropInfo.cs
UnfilteredInsertIndex returns incorrect index when item dropped at the end of a filtered list. This modification fixes this fault.
> Edited UnfilteredInsertIndex property

- src/GongSolutions.WPF.DragDrop.Shared/DefaultDropHandler.cs
- src/GongSolutions.WPF.DragDrop.Shared/DragDrop.Properties.cs
- src/GongSolutions.WPF.DragDrop.Shared/Utilities/ItemsControlExtensions.cs
- src/Showcase.WPF.DragDrop.NET45/Views/MixedSamples.xaml
- New attached property `SelectDroppedItems`. If this is set to true all dropped items will be selected again after drag&drop action (by using the default drop handler).
- New static method `SelectDroppedItems` which can be used together with a drop info and the items which are should be selected.
- New static method `ClearSelectedItems` for `ItemsControl`
Closes #176 
Relates to #176
> New Feature: Select dropped items after drag&drop action

- src/GongSolutions.WPF.DragDrop.Shared/DragDrop.cs
- src/GongSolutions.WPF.DragDrop.Shared/DropTargetInsertionAdorner.cs
- src/Showcase.WPF.DragDrop.NET45/Views/DataGridSamples.xaml
- src/Showcase.WPF.DragDrop.NET45/Views/ListViewSamples.xaml
The insertion adorner was painted at wrong position. Now the adorner tries to get the header and calculates the right position for the adorner.
> Fix DropTargetInsertionAdorner for empty DataGrid and ListView

- src/GongSolutions.WPF.DragDrop.Shared/DropInfo.cs
- src/GongSolutions.WPF.DragDrop.Shared/Utilities/DragDropExtensions.cs
see issue #283
DropPosition is relative to parent items control, therefore it needs to be recalculated to be relative to the child item, i.e. the ItemContainer. E.g.:
Outer ListView with 5 rows, each row has a Height of 100, inner ListViews respectively. Lets say DropPosition is on third row of outer ListView, and has coordinates X=50, Y=250. The inner ListView ist under the DropPosition. Now the ItemContainer's Y-Bound is [0, 100], DropPosition's Y-coordinate is 250 => DropPosition is not in the descendant bounds.
Fix: get the ItemContainer's position relative to the Parent's (0,0)-Coordinate an subtract the ItemContainer's relative coordinates from the DropPosition coordinates
> Nested list view drop target

- src/GongSolutions.WPF.DragDrop.Shared/DragDrop.Properties.cs
- src/GongSolutions.WPF.DragDrop.Shared/DragDrop.cs
- src/GongSolutions.WPF.DragDrop.Shared/DropInfo.cs
- src/GongSolutions.WPF.DragDrop.Shared/EventType.cs
- src/GongSolutions.WPF.DragDrop.Shared/GongSolutions.WPF.DragDrop.Shared.projitems
- src/GongSolutions.WPF.DragDrop.Shared/IDropInfo.cs
With this version, there is a new dependency property `DropEventType` to specify which events should be handled for the IDropTarget:
* `Auto` - The default value and the current implementation which uses the preview events if the control is an ItemsControl and the normal events otherwise
* `Tunneled` - DragDrop will always subscribe to the tunneled (Preview) events
* `Bubbled` - DragDrop will always subscribe to the bubbled events
* `TunneledBubbled` - DragDrop will subscribe to the tunneled and the bubbled events
Also the `IDropInfo` interface has a new property `EventType` which shows from which event the IDropInfo object was created. It has the value `Tunneled` if it was created from a Preview event or `Bubbled` if it was created from a bubbled event.
This is needed for the event type …
> Add dependency property DropEventType

- src/GongSolutions.WPF.DragDrop.Shared/DragDrop.Properties.cs
- src/GongSolutions.WPF.DragDrop.Shared/DropInfo.cs
I added an attached property called `DropTargetScrollViewer`.
It is helpful if you have a ScrollViewer wrapping several elements (that have their own ScrollViewers) and you want the outer ScrollViewer to scroll automatically when hovering at the edge of the view.
I've needed this twice now, so I figured it might be worth a PR.
> Added DropTargetScrollViewer property

- src/GongSolutions.WPF.DragDrop.Shared/DropTargetInsertionAdorner.cs
- src/GongSolutions.WPF.DragDrop.Shared/Utilities/ItemsControlExtensions.cs
ViewportWidth is not sometimes right at the time of non-indication ScrollBar
DropTargetInsertionAdorner  is short
> Sample
```
<Grid Width="500">
<Grid.ColumnDefinitions>
<ColumnDefinition Width="Auto" />
</Grid.ColumnDefinitions>
<ListView MinWidth="150"
dd:DragDrop.IsDragSource="True"
dd:DragDrop.IsDropTarget="True"
dd:DragDrop.UseDefaultEffectDataTemplate="True">
<ListViewItem>Unbound Item1</ListViewItem>
<ListViewItem>Unbound Item2</ListViewItem>
<ListViewItem>Unbound Item3</ListViewItem>
<ListViewItem>Unbound Item4</ListViewItem>
<ListViewItem>Unbound Item5</ListViewItem>
</ListView>
</Grid>
```
> DropTargetInsertionAdorner  is short

- src/GongSolutions.WPF.DragDrop.Shared/DragDrop.cs
- src/GongSolutions.WPF.DragDrop.Shared/Utilities/DragDropExtensions.cs
DragInfo useful in custom drag adorner template selectors for accessing visual tree. E.g.: in nested ListBox scenario, if dragging an item of inner ListBox onto outer ListBox, it could be that not only the selected item should be moved but the whole group. The drag adorner should not only show the screen capture of the selected item but the screen capture of its parent, the whole ListBox. Therefore the capture screen data template creation functionality is moved to DragDropExtensions.
> Make dragInfo available in custom drag adorner template selector

- src/Showcase/ViewModels/MainViewModel.cs
When clicking on the URL link icon to open GitHub issues, the demo app crashes.
This is a difference between .NET Core and .NET Framework. Because we targets both .NET Core and .NET Framework so this issue should be fixed.
See my post for more details:
- [What is the UseShellExecute in processes starting? What's the difference of its behavior on .NET Core and .NET Framework - walterlv](https://blog.walterlv.com/post/use-shell-execute-in-process-start-info.html)
> Fix the file not found exception in opening urls.

- src/GongSolutions.WPF.DragDrop/DefaultDropHandler.cs
In the `DefaultDropHandler`:
`TestCompatibleTypes` does not consider any `IEditableCollectionView`:
```c#
...
else
{
return target is IList;
}
```
This causes `CanAcceptData` to always reject any targets that are `IEditableCollectionView`, however `Drop` is able to handle them.
I simply modified it to: 
```c#
return target is IList || target is IEditableCollectionView;
```
I also added some minor cleanups for the same function.
> Fix DefaultDropHandler.TestCompatibleTypes for any IEditableCollectionView

- src/GongSolutions.WPF.DragDrop/DragDrop.Properties.cs
- src/GongSolutions.WPF.DragDrop/DragDrop.cs
- src/GongSolutions.WPF.DragDrop/DragInfo.cs
- src/GongSolutions.WPF.DragDrop/Utilities/HitTestUtilities.cs
The goal of this PR was to implement the feature "Touch drag & drop" that is linked to the old issue #110. Now we can do a drag and drop with a touch screen without doing the workaround presented in the issue.
We add the three events `PreviewTouchDown`, `PreviewTouchUp` and `PreviewTouchMove` where we do approximatively the same stuff as for the mouse events.
The way to get the position is different between the mouse and the touch, so we need to change some methods so that they can accept a `TouchEventArgs` and not only a `MouseButtonEventArgs`. We needed to change the `DragInfo` constructor so that we can initialize the object with both events.
> Implement drag drop touch screen

- src/GongSolutions.WPF.DragDrop/DragAdorner.cs
- src/GongSolutions.WPF.DragDrop/DragDrop.cs
Use ScrollToHorizontalOffset and ScrollToVerticalOffset instead the LineLeft, LineRight, LineUp and LineDown methods to prevent a scrolling issue with the Adorners.
This was reported by @KeithSwanger on Gitter channel.
> Fix scrolling issues if ScrollViewer CanContentScroll is set true

- src/GongSolutions.WPF.DragDrop/DragDrop.Properties.cs
- src/GongSolutions.WPF.DragDrop/DragDrop.cs
- src/GongSolutions.WPF.DragDrop/Utilities/IRootElementFinder.cs
- src/GongSolutions.WPF.DragDrop/Utilities/RootElementFinder.cs
This adds support for providing a custom RootElementFinder, rather than the static version that exists in the project.
We use GongDragDrop in a project that is also using AvalonDock.  When floating windows, we found that the existing code is incorrectly finding a HwndHost as the root element due to how they setting it as the content here:
https://github.com/xceedsoftware/wpftoolkit/blob/master/ExtendedWPFToolkitSolution/Src/Xceed.Wpf.AvalonDock/Controls/LayoutFloatingWindowControl.cs
We'd be able to work around that edge case (which doesn't quite seem correct), if we had a way to provide our own logic for the RootElementFinder for this particular instance.
> Support using a custom RootElementFinder

- src/GongSolutions.WPF.DragDrop/DragDrop.cs
- Don't use ScrollToHorizontalOffset and ScrollToVerticalOffset
- Move the adorner after scrolling the ScrollViewer
> Fix moving Adorner while ScrollViewer is scrolling

- src/GongSolutions.WPF.DragDrop/DefaultDropHandler.cs
- src/GongSolutions.WPF.DragDrop/DragDrop.Properties.cs
- src/GongSolutions.WPF.DragDrop/DragDrop.cs
- src/GongSolutions.WPF.DragDrop/DropTargetHighlightAdorner.cs
- src/GongSolutions.WPF.DragDrop/GongSolutions.WPF.DragDrop.csproj
- src/GongSolutions.WPF.DragDrop/Utilities/IRootElementFinder.cs
- src/GongSolutions.WPF.DragDrop/Utilities/RootElementFinder.cs
I fixed some namespace issues.
The new `IRootElementFinder` used a different namespace than the rest of the project, due to capitalizing WPF. I changed the `RootNamespace` in the project file so that this shouldn't happen again in the future.
Also removed a couple of using directives that were not required.
> Fixed namespace issues

- src/Directory.build.props
- src/GongSolutions.WPF.DragDrop/Utilities/DpiHelper.cs
- src/GongSolutions.WPF.DragDrop/Utilities/DragDropExtensions.cs
- src/Showcase/App.net462.config
Use VisualTreeHelper.GetDpi for newer frameworks (>= .Net 4.6.2)
> Fix DpiHelper usage

- src/GongSolutions.WPF.DragDrop/DragInfo.cs
Fix testing of DragSourceIgnored for an item if DragDirectlySelectedOnly is set to false.
Closes #350
> Fix testing of DragSourceIgnored for an item if DragDirectlySelectedOnly is set to false

- src/GongSolutions.WPF.DragDrop/DragDrop.Properties.cs
- src/GongSolutions.WPF.DragDrop/DragDrop.cs
- src/GongSolutions.WPF.DragDrop/DropInfo.cs
- src/GongSolutions.WPF.DragDrop/IDragEnumerableSorter.cs
- src/GongSolutions.WPF.DragDrop/IDragPreviewItemsSorter.cs
- src/GongSolutions.WPF.DragDrop/IDropTargetItemsSorter.cs
- src/Showcase/ViewModels/MainViewModel.cs
- src/Showcase/Views/MixedSamples.xaml
* Added method for users to sort the items that will be shown in the drag/drop preview. This lets them show a nicer preview to the end user while they are dragging items. In my use case, my users are dragging numbered items, and when they select multiple items out of order, I would like the preview to show the items in numbered order rather than in the order they selected the items.
* Added `IDragPreviewItemsSorter` as an interface for objects that can sort the drag preview items
* Added `DragPreviewItemsSorter` property so you can set this up in your xaml
* Added `IDropTargetItemsSorter` as an interface for objects that want to sort items before they are dropped on a target
* Added `DropTargetItemsSorter` property so you can set up the `IDropTargetItemsSorter` in your xaml as needed
* …
> Feature: sort drag drop preview items

- README.md
Just a minor README update to show .NET 5 compatibility (🥳). My suggestion would be to not merge this until 2.4.0 is released so that there is no confusion between what is in the README and what is on NuGet.
> Update README to show .NET 5 compat

- src/GongSolutions.WPF.DragDrop/Utilities/ItemsControlExtensions.cs
- src/Showcase/Views/ListBoxSamples.xaml
I added better handling of `UniformGrid` panels. I also added a new sample page in the showcase to test it.
Before this change, when using `UniformGrid` as the items panel on i.e. a `ListBox`, the drop target adorner would default to vertical orientation, since it has no `Orientation` property. However `UniformGrid` has a horizontal flow, except when there is only 1 column.
> Better handling of UniformGrid panels

- src/GongSolutions.WPF.DragDrop/DragDrop.cs
This should hopefully fix issue #336.
* Fixed DragSourceUp() method using incorrect ItemsControl instance for item selection on mouse-up (relates to nested ItemsControls, eg RowDetails for DataGrid).
* Updated DragSourceUp() method to set the selected item for the sender object if it is an ItemsControl but is not the VisualSource of the DragInfo instance (relates to nested ItemsControls, eg RowDetails for DataGrid).
> Fix nested ItemsControl behaviour issues highlighted in issue #336

- src/GongSolutions.WPF.DragDrop/Utilities/ItemsControlExtensions.cs
When a change to the selection of WPF's `DataGrid` is made programmatically it does not update the selection anchor, which is used for SHIFT selection.  As a result, attempting SHIFT selection following a programmatic adjustment to the selection of a `DataGrid` can result in unexpected selection behaviour for the end user.
You can test this behaviour in the Showcase application by:
1.  Select a row (eg row 3).
2. Hold SHIFT and click on a row a few rows down from the first selected row (eg row 9).
3. Let go of SHIFT and then click on a row in the middle of the selection (eg row 5).
4. Hold SHIFT and click on a row a few rows down (eg row 12) from the currently selected row.
Without the fix in this pull request, the selection will select all the rows from row 3 to row 12, instead of row 5 …
> Fix DataGrid row anchor not being set when programmatically updating selection

- src/GongSolutions.WPF.DragDrop/Utilities/ItemsControlExtensions.cs
In the `SetSelectedItem()` method of `ItemsControlExtensions`, it sets the `SelectedItem` to `null` before setting it to the value passed in.  For an existing multi-selection, the value being selected could already be within that existing selection, meaning that the item we wish to select is being deselected and then selected again.
This behaviour can make `SelectionChanged` event handling somewhat problematic further down the line (an application I'm working manages what selection behaviour in the `SelectionChanged` events for nested `DataGrid instances, and the deselection of all rows, followed by the selection of the correct one for the parent `DataGrid` had implications for the child `DataGrid` instance's selected rows.  This relates to the other pull request I've raised, …
> Fix brief deselection of selected item to be selected when changing selected item.

- src/GongSolutions.WPF.DragDrop/DragDrop.cs
- src/GongSolutions.WPF.DragDrop/DropTargetHighlightAdorner.cs
- src/GongSolutions.WPF.DragDrop/Utilities/DragDropExtensions.cs
- src/GongSolutions.WPF.DragDrop/Utilities/Microsoft WPF License.txt
- src/GongSolutions.WPF.DragDrop/Utilities/VisualTreeDescendantBoundsHelper.cs
- src/GongSolutions.WPF.DragDrop/Utilities/VisualTreeExtensions.cs
`VisualTreeHelper.GetDescendantBounds()` does not account for collapsed descendants, resulting in various rendering issues when dealing with drag and drop functionality for elements that can have collapsed components (ie `TreeViewItem` instances and `DataGridRow` instances with row details).  Further details can be found [here](https://github.com/dotnet/wpf/issues/5057#issuecomment-897146992).
* Added VisualTreeDescendantBoundsHelper to work around bug/feature of VisualTreeHelper.GetDescendantBounds() including collapsed Visuals in its bounds calculations.
Closes #346
> Added bounds calculation workaround

- src/GongSolutions.WPF.DragDrop/DragDrop.cs
- src/GongSolutions.WPF.DragDrop/DropInfo.cs
- src/GongSolutions.WPF.DragDrop/Utilities/VisualTreeExtensions.cs
- src/Showcase/Views/Issues.xaml
- Fix item selection/deselection in ItemsControl (inside TabControl) when multiple/extended selection is enabled
- Improve GetVisualDescendent and GetVisualDescendents method with searching for a child name
- Fix IsSameDragDropContextAsSource calculation
Closes #336
> Fix item selection/deselection in ItemsControl (inside TabControl) when multiple/extended selection is enabled

- src/GongSolutions.WPF.DragDrop/DragDrop.cs
- src/GongSolutions.WPF.DragDrop/DragDropPreview.cs
- src/GongSolutions.WPF.DragDrop/Utilities/DragDropExtensions.cs
- src/Showcase/Views/SettingsView.xaml
This PR fixes the issue with the drag preview which doesn't show up if the source is not a target.
_Describe the changes you have made to improve this project._
The preview will now created before the drag operation will be started.
Closes #389
> Fix for drag preview doesn't show up if the source is not a target

- src/GongSolutions.WPF.DragDrop/DragDrop.Properties.cs
- src/GongSolutions.WPF.DragDrop/DragDrop.cs
- src/GongSolutions.WPF.DragDrop/DragInfo.cs
- src/GongSolutions.WPF.DragDrop/GongSolutions.WPF.DragDrop.csproj
- src/GongSolutions.WPF.DragDrop/IDragInfoBuilder.cs
`IDragInfoBuilder` enables the specification of a `IDragInfo` factory to handle unsupported 3rd party controls.
User can opt-in into this interface by adding the right binding in XAML: `dd:DragDrop.DragInfoBuilder="{Binding}"`
Added `IDragInfoBuilder` interface and `DragInfoBuilder` dependency property.
When `IDragInfoBuilder` is specified, the code calls the appropriate member from it to create the DragInfo object. 
If this call returns null, it uses the regular DragInfo construction code. Same thing happens if when IDragInfoBuilder is NOT specified.
`IDragInfoBuilder.CreateDragInfo` is where custom code can be specified to handle the correct creation of DragInfo objects for custom controls.
For instance, I need to support Telerik's RadTreeListView but the same mechanism can be applied …
> Enable support for 3rd party controls.

- src/GongSolutions.WPF.DragDrop/DragDrop.cs
- src/GongSolutions.WPF.DragDrop/DragInfo.cs
- src/GongSolutions.WPF.DragDrop/DropInfo.cs
- src/GongSolutions.WPF.DragDrop/IDragInfoBuilder.cs
- src/GongSolutions.WPF.DragDrop/IDropInfoBuilder.cs
- Simplify IDragInfoBuilder creation
- Update documentation of IDropInfoBuilder
**_IDragInfoBuilder_**
```csharp
/// <summary>
/// Interface implemented by Drag Info Builders.
/// It enables custom construction of DragInfo objects to support 3rd party controls like DevExpress, Telerik, etc.
/// </summary>
public interface IDragInfoBuilder
{
/// <summary>
/// Initializes a new instance of the DragInfo class.
/// </summary>
/// <param name="sender">The sender of the input event that initiated the drag operation.</param>
/// <param name="originalSource">The original source of the input event.</param>
/// <param name="mouseButton">The mouse button which was used for the drag operation.</param>
/// <param name="getPosition">A function of the input event which is used to get drag position …
```
> Simplify IDragInfoBuilder and update documentation

- src/GongSolutions.WPF.DragDrop/DragDrop.Properties.cs
- src/GongSolutions.WPF.DragDrop/DragDrop.cs
- src/GongSolutions.WPF.DragDrop/DragDropPreview.cs
Add DragAdorner and DropAdorner DataTemplate/Selector for multiple item selection
`dd:DragDrop.DragAdornerMultiItemTemplate="{StaticResource MultiItemTemplate}"`
`dd:DragDrop.DropAdornerMultiItemTemplate="{StaticResource MultiItemTemplate}"`
Sample
```xaml
<ListBox x:Name="SampleListBox"
dd:DragDrop.IsDragSource="True"
dd:DragDrop.IsDropTarget="True"
dd:DragDrop.DragAdornerMultiItemTemplate="{StaticResource MultiItemTemplate}"
dd:DragDrop.DropAdornerMultiItemTemplate="{StaticResource MultiItemTemplate}"
ItemsSource="{Binding SampleDataCollection}" />
```
With this properties it's possible to set different template for multiple selected items. If no template is set then the single templates are used.
Closes #228
> Add DragAdorner and DropAdorner DataTemplate/Selector for multiple item selection

- src/GongSolutions.WPF.DragDrop/DragDrop.cs
- src/Showcase/Models/ItemModel.cs
- src/Showcase/Views/Issues.xaml
_Describe the changes you have made to improve this project._
- change sample from #342
- enable dragging ToggleButton controls
With changes for #342 the dragging of ToggleButton controls was gone. To re-enable this it's necessary to remove the test in GetHitTestResult and don't handle the mouse inputs for it (down and up). So after that it's possible to toggle the state or drag the control.
Closes #420
> Enable dragging of ToggleButton controls

- src/GongSolutions.WPF.DragDrop/DragDrop.cs
This fixes the drag adorner getting stuck when the user cancels a drag by also pressing the other mouse button.
Demonstration of the issue:
Fixes #425
> Cancel drag when both mouse buttons are pressed

- src/GongSolutions.WPF.DragDrop/DragDrop.Properties.cs
- src/GongSolutions.WPF.DragDrop/DragDrop.cs
The thickness of the Pen stroke is set to a fixed value. This can be hard to see for people who are vision impaired, so increasing its value is beneficial.
> Add DropTargetAdornerPenProperty

- src/Directory.build.props
- src/GongSolutions.WPF.DragDrop/Directory.Build.props
- src/GongSolutions.WPF.DragDrop/GongSolutions.WPF.DragDrop.csproj
NuGet comes with the message: The uploaded symbols package contains one or more pdbs that are not portable. So this will hopefully fix this.
> Fix symbols package

- src/GongSolutions.WPF.DragDrop/DragDrop.Properties.cs
- src/GongSolutions.WPF.DragDrop/DragDrop.cs
- src/GongSolutions.WPF.DragDrop/Utilities/MouseHelper.cs
- src/Showcase/Views/ListBoxSamples.xaml
- src/Showcase/Views/SettingsView.xaml
Added the code @KKauK suggested in #418 and enhanced Showcase to test touch. I was able to test on a touch panel and after the adjustments it works fine.
Closes #418
> fix touch support 

- src/GongSolutions.WPF.DragDrop/Utilities/TypeUtilities.cs
- src/Showcase/Models/ItemModel.cs
- src/Showcase/Models/SampleData.cs
Currently, If `collection` is subclass of `ObservableCollection<>`, `IsObservableCollection(collection)` returns false.
But I hope the method call returns true.
Sample
```cs
void Check()
{
var result = new StringObservableCollection().IsObservableCollection();
// I hope result is true, but it's false.
}
class StringObservableCollection : ObservableCollection<string> { }
```
> Check subclass of ObservableCollection<>

- src/GongSolutions.WPF.DragDrop/DefaultDropHandler.cs
- src/GongSolutions.WPF.DragDrop/ICloneableDragItem.cs
- src/GongSolutions.WPF.DragDrop/IDragItemCloneable.cs
- src/GongSolutions.WPF.DragDrop/IDragItemSource.cs
_Describe the changes you have made to improve this project._
Add own cloneable interface for easier handling:
```csharp
/// <summary>
/// Supports cloning like the ICloneable interface, which creates a new instance of a class with the same value as an existing instance.
/// </summary>
public interface ICloneableDragItem
{
/// <summary>
/// Creates a new object that is a copy of the current instance.
/// </summary>
/// <param name="dropInfo">Object which contains several drop information.</param>
/// <returns>A new object that is a copy of this instance.</returns>
object CloneItem(IDropInfo dropInfo);
}
```
Add also a new interface for easier handling after item was dropped.
```csharp
/// <summary>
/// Supports methods for models which can be dropped.
/// </summary>
public interface …
```
> Add own cloneable interface for easier handling

- src/GongSolutions.WPF.DragDrop/DragDrop.Properties.cs
- src/GongSolutions.WPF.DragDrop/DragDrop.cs
Move code for resetting of drag preview states into cancellation handling, so it is always executed.
Fixes #493
> Always correctly reset state when drag is cancelled

- src/GongSolutions.WPF.DragDrop/DropTargetAdorner.cs
If you have multi-threaded windows, the detach call can cause an InvalidOperationException.
This change is checking for access, otherwise marshalling the call to the associated dispatcher of the AdornerLayer
> Threading Problem

- src/GongSolutions.WPF.DragDrop/DragDrop.Properties.cs
- src/GongSolutions.WPF.DragDrop/DragDrop.cs
- src/GongSolutions.WPF.DragDrop/DragInfo.cs
- src/GongSolutions.WPF.DragDrop/DropInfo.cs
- src/GongSolutions.WPF.DragDrop/DropTargetAdorner.cs
- src/GongSolutions.WPF.DragDrop/DropTargetInsertionAdorner.cs
- src/GongSolutions.WPF.DragDrop/IDragInfo.cs
- src/GongSolutions.WPF.DragDrop/IDragInfoBuilder.cs
- src/GongSolutions.WPF.DragDrop/IDragSource.cs
- src/GongSolutions.WPF.DragDrop/IDropInfoBuilder.cs
- src/GongSolutions.WPF.DragDrop/IDropTarget.cs
- src/Showcase/Models/TextBoxCustomDropHandler.cs
The new `IDragInfoBuilder` and `IDropInfoBuilder` are great, but there are still some scenarios where it's not possible to override default behavior.
This PR further embraces the `IDragInfo` and `IDropInfo` interfaces, enabling more custom implementations.
I needed this when implementing drag-n-drop for a custom multi selection tree view.
- `IDragInfoBuilder.CreateDragInfo` now returns `IDragInfo` instead of `DragInfo`
- `IDropInfoBuilder.CreateDropInfo` now takes an `IDragInfo` instead of `DragInfo`
- `RefreshSourceItems` method added to `IDragInfo`. This is not really a breaking change, as up until this PR, it wasn't possible to use a fully custom implementation of `IDragInfo` and any existing implementations will be inheriting from `DragInfo`.
> Enable custom IDragInfo & IDropInfo implementations
